FROM python:3.10-alpine as base

# <!-- mqm
FROM base as mqm

RUN apk add --no-cache wget
RUN mkdir /tmp/mqm && cd /tmp/mqm && \
    wget -q --show-progress https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqdev/redist/9.2.2.0-IBM-MQC-Redist-LinuxX64.tar.gz -O - | tar xzf -

RUN mkdir -p /opt/mqm/inc \
    && mkdir -p /opt/mqm/lib \
    && mkdir -p /opt/mqm/lib64 \
    && mkdir -p /opt/mqm/gskit8/lib64 \
    && mkdir -p /opt/mqm/msg/en_US

RUN cp /tmp/mqm/inc/*.h* /opt/mqm/inc/ \
    && cp /tmp/mqm/lib/libcurl.so /opt/mqm/lib/ \
    && cp /tmp/mqm/lib/ccsid*.tbl /opt/mqm/lib/ \
    && cp /tmp/mqm/lib64/libmq*_r.so /opt/mqm/lib64/ \
    && cp -r /tmp/mqm/gskit8/lib64 /opt/mqm/gskit8/ \
    && cp /tmp/mqm/msg/en_US/amq.cat /opt/mqm/msg/en_US/
# mqm -->

# <!-- python
FROM base AS python

RUN apk add --no-cache \
    openssh-client-default \
    git \
    gcc \
    g++ \
    musl-dev \
    libffi-dev \
    cmake \
    make \
    openssl-dev \
    python3-dev

COPY --from=mqm /opt/mqm /opt/mqm

ENV LD_LIBRARY_PATH="/opt/mqm/lib64:${LD_LIBRARY_PATH}"
ENV LC_ALL=C
ENV LANG=C

RUN mkdir -p -m 0600 /root/.ssh

RUN python -m venv /opt/python-env

ENV PATH="/opt/python-env/bin:$PATH"

COPY requirements.txt /tmp

RUN --mount=type=ssh GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=no' pip --disable-pip-version-check --no-cache-dir install -r /tmp/requirements.txt
# python -->

# <!-- entrypoint
FROM base AS entrypoint

RUN echo $'#!/usr/bin/env sh\n\
set -e\n\
\n\
stty rows $LINES cols $COLUMNS\n\
\n\
exec behave "$@"' >> /grizzly-entrypoint.sh

RUN chmod +x /grizzly-entrypoint.sh
# entrypoint -->

# <!-- grizzly
FROM base

ARG GRIZZLY_UID
ARG GRIZZLY_GID

RUN addgroup \
        -g "${GRIZZLY_GID}" \
        grizzly \
    && \
    adduser \
        -u "${GRIZZLY_UID}" \
        -G grizzly \
        -s /bin/sh \
        -D \
        grizzly

RUN apk add --no-cache lsof gcompat

COPY --from=mqm /opt/mqm /opt/mqm
COPY --from=python --chown=grizzly:grizzly /opt/python-env /opt/python-env
COPY --from=entrypoint /grizzly-entrypoint.sh /grizzly-entrypoint.sh

ENV LD_LIBRARY_PATH="/opt/mqm/lib64:${LD_LIBRARY_PATH}"
ENV LC_ALL=C
ENV LANG=C
ENV PATH="/opt/python-env/bin:$PATH"
ENV PYTHONUNBUFFERED=1

RUN mkdir -p /home/grizzly/IBM/MQ/data && \
    chown -R grizzly:grizzly /home/grizzly \
    && mkdir -p /srv/grizzly/features/logs \
    && ln -sf /srv/grizzly/features/logs /home/grizzly/IBM/MQ/data/errors \
    && rm -rf /srv/grizzly/features

USER grizzly

ENTRYPOINT ["./grizzly-entrypoint.sh"]
# grizzly -->
