name: code quality

on:
  pull_request:
    branches:
    - main

jobs:
  linting:
    name: linting
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    env:
      PYTHONPATH: .

    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v2

    - name: setup python
      id: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: install python dependencies
      id: pip
      run: python -m pip install .[dev]

    - name: pylint
      id: pylint
      run: python -m pylint --jobs=0 --fail-under=10 grizzly_cli/ tests/

    - name: mypy
      id: mypy
      run: python -m mypy grizzly_cli/ tests/

    - name: flake8
      id: flake8
      run: python -m flake8

  test-and-coverage:
    name: test-and-coverage/${{ matrix.runs-on }}-python-${{ matrix.python-version }}
    runs-on: ${{ matrix.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
        runs-on: ['ubuntu-latest']
        include:
          - python-version: '3.10'
            runs-on: windows-latest

    env:
      PYTHONPATH: .

    steps:
    - name: timezone
      id: timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Stockholm"
        timezoneWindows: "W. Europe Standard Time"

    - name: checkout
      id: checkout
      uses: actions/checkout@v2

    - name: setup python
      id: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: install python dependencies
      id: pip
      run: python -m pip install .[dev]

    - name: pytest
      id: pytest
      run: python -m pytest

    - name: coverage
      id: coverage
      run: python -m coverage report --fail-under=95

  documentation-scripts:
    name: "documentation/${{ matrix.script }}"
    runs-on: 'ubuntu-latest'

    strategy:
      fail-fast: false
      matrix:
        script:
        - script/docs-generate-licenses.py

    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v2

    - name: setup python
      id: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: install python dependencies
      id: pip
      run: python -m pip install --upgrade .[dev]

    - name: exists
      run: test -e ${{ matrix.script }}

    - name: executable
      run: test -x ${{ matrix.script }}

    - name: runnable
      run: ./${{ matrix.script }} &> /dev/null
