name: code quality

on:
  pull_request:
    branches:
    - main

jobs:
  code-quality:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version: [3.6]

    env:
      PYTHONPATH: .

    steps:
    - name: setup environment
      id: env
      run: |
        sudo ln -fs /usr/share/zoneinfo/Europe/Stockholm /etc/localtime
        sudo ln -fs /usr/share/zoneinfo/Europe/Stockholm /etc/timezone
        echo $HOME/.local/bin >> $GITHUB_PATH

    - name: checkout
      id: checkout
      uses: actions/checkout@v2

    - name: setup python (with cache)
      if: ${{ !env.ACT }}
      id: setup-python-with-cache
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: '**/requirements-dev.txt'

    - name: setup python (without cache)
      if: ${{ env.ACT }}
      id: setup-python-without-cache
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: install python dependencies
      id: pip
      run: |
        pip install --upgrade wheel
        pip install --upgrade --upgrade-strategy eager -r <(cat requirements.txt requirements-dev.txt)

    - name: run pytest
      id: pytest
      run: |
        pytest

    - name: run coverage
      id: coverage
      run: |
        coverage report --fail-under=95

    - name: run pylint
      id: pylint
      run: |
        pylint --jobs=0 --fail-under=10 grizzly_cli/ tests/

    - name: run mypy
      id: mypy
      run: |
        mypy grizzly_cli/ tests/
