name: code quality

on:
  pull_request:
    branches:
    - main

jobs:
  code-quality:
    name: ${{ matrix.runs-on }}-python-${{ matrix.python-version }}
    runs-on: ${{ matrix.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
        runs-on: ['ubuntu-latest']
        include:
          - python-version: '3.10'
            runs-on: windows-latest

    env:
      PYTHONPATH: .

    steps:
    - name: timezone
      id: timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Stockholm"
        timezoneWindows: "W. Europe Standard Time"

    - name: checkout
      id: checkout
      uses: actions/checkout@v2

    - name: setup python
      id: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: install python dependencies
      id: pip
      run: |
        python -m pip install .[dev]

    - name: run pytest
      id: pytest
      run: |
        python -m pytest

    - name: run coverage
      id: coverage
      run: |
        python -m coverage report --fail-under=95

    - name: run pylint
      id: pylint
      run: |
        python -m pylint --jobs=0 --fail-under=10 grizzly_cli/ tests/

    - name: run mypy
      id: mypy
      run: |
        python -m mypy grizzly_cli/ tests/

    - name: run flake8
      id: flake8
      run: |
        python -m flake8
